# Generated by Django 4.2.8 on 2023-12-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkuser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='linkuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='linkuser',
            name='updated',
        ),
    ]
