# Generated by Django 4.2.8 on 2023-12-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkuser',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='linkuser',
            name='is_public',
        ),
    ]
