# Generated by Django 4.2.8 on 2023-12-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_linkuser_is_favorite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='slug',
            new_name='url',
        ),
    ]
